version: '3.5'

networks:
  proxy:
    external: true

services:
  once_composer:
    container_name: once_composer
    image: composer:latest
    restart: "no"
    volumes:
      - .:/app
    command: install --ignore-platform-reqs
    networks:
      - proxy
    labels:
      - traefik.enabled=false
      - traefik.docker.network=proxy

  once_php:
    container_name: once_php
    depends_on:
      - once_db
    build:
      context: docker/php
    volumes:
      - ./:/var/www/html:cached
    expose:
      - 9001
    ports:
      - 9000:9000
    environment:
      - PHP_XDEBUG_ENABLED=false
      - APP_ENV=prod
    networks:
      - proxy
    labels:
      - traefik.enabled=false
      - traefik.docker.network=proxy

  once_db:
    container_name: once_db
    build:
      context: docker/postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=qwe123
    networks:
      - proxy
    labels:
      - traefik.enabled=false
      - traefik.docker.network=proxy

  once_nginx:
    container_name: once_nginx
    depends_on:
      - once_php
    image: nginx:latest
    networks:
      - proxy
    volumes:
      - ${PATH_LOCAL}:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - traefik.http.routers.webro.rule=Host(`${HTTP_HOST}`, `www.${HTTP_HOST}`)
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.http.routers.webro.tls=true
