version: '3.5'

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_ADDRESS}

services:
  once_composer:
    container_name: once_composer
    image: composer:latest
    restart: "no"
    volumes:
      - .:/app
    command: install --ignore-platform-reqs

  once_php:
    container_name: once_php
    depends_on:
      - once_db
    build:
      context: docker/php
    volumes:
      - ${PATH_LOCAL}:/var/www/html:cached
    expose:
      - 9001
    ports:
      - 9000:9000
    environment:
      - PHP_XDEBUG_ENABLED=${XDEBUG_ENABLED}
      - APP_ENV=${APP_ENV}
      - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}

  once_db:
    container_name: once_db
    build:
      context: docker/postgres
    ports:
      - ${POSTGRESS_LOCAL_PORT}:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=qwe123

  once_nginx:
    container_name: once_nginx
    depends_on:
      - once_php
    image: nginx:latest
    ports:
      - ${NGINX_LOCAL_PORT}:80
    volumes:
      - ${PATH_LOCAL}:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf