index:
  path: /
  controller: App\Controller\Main::description

createMessage:
  path: /create
  controller: App\Controller\Main::createMessage

readMessage:
  path: /read/{messageUuid}
  controller: App\Controller\Main::readMessage